import { KEYWORD } from './keywords';
import { Catalogue } from './catalogue';

/**
 * The type of the keyword.
 */
export enum TYPE {
    /**
     * _Reserved_ keywords are usable only as a _ColLabel_. They cannot be
     * distinguished from variable, type, or function names in some contexts.
     */
    RESERVED,
    /**
     * _Command_ keywords are reserved by PostgreSQL for commands. They cannot
     * be distinguished from variable, type, or function names in most context.
     */
    COMMAND,
    /**
     * _Unreserved_ keywords are available for use as any kind of name.
     */
    UNRESERVED,
    /**
     * _Column Name_ keywords can be column, table, etc names.
     *
     * Many of these keywords will be recognized as type or function
     * names too, but they have special productions for the purpose and so
     * can't be treated as "generic" type or function names.
     *
     * These names are not usable as function names because they can be followed by
     * `(` in typename productions, which looks too much like a function call
     * for an `LR(1)` parser.
     */
    COL_NAME,
    /**
     * _TYPE_FUNC_NAME_ keywords can be type or function names.
     *
     * Most of these are keywords that are used as operators in expressions.
     * In general such keywords can't be column names because they would be
     * ambiguous with variables, but they are unambiguous as function identifiers.
     *
     * Do not include `POSITION`, `SUBSTRING`, etc here since they have explicit
     * productions in `a_expr` to support the goofy `SQL9x` argument syntax.
     * - Thomas 2000-11-28
     */
    TYPE_FUNC_NAME
}

/**
 * Keywords that can be used as a `bare_label` (i.e. keywords that
 * can be used as column names when not preceded by `AS`) have this
 * property set to `true`.
 *
 * A keywords is marked as BARE_LABEL in its {@link MAKE_KEYWORD}
 * function below.
 */
export const BARE_LABEL = true;

/**
 * Mark keyword as `BARE_LABEL` if it is included in
 * {@link KEYWORD.BARE_LABEL}, or `AS_LABEL` if it is not.
 */
export const AS_LABEL = false;

/**
 * Defines a postgresql keyword
 */
export declare interface PG_KEYWORD {
    id: KEYWORD;

    /**
     * A keyword can be one of...
     *
     * | Type                        | Description                                                                                 |
     * | --------------------------- | ------------------------------------------------------------------------------------------- |
     * | {@link TYPE.RESERVED}       | Usable only as a _ColLabel_.                                                                |
     * | {@link TYPE.UNRESERVED}     | Available for use as any kind of name.                                                      |
     * | {@link TYPE.COL_NAME}       | Can be column, table, etc names.                                                            |
     * | {@link TYPE.TYPE_FUNC_NAME} | Can be type or function names. Most are keywords that are used as operators in expressions. |
     **/
    type: TYPE;
    /**
     * Keywords that can be used as a `bare_label` (i.e. keywords that
     * can be used as column names when not preceded by `AS`) have this
     * property set to `true`.
     *
     * A keywords is marked as BARE_LABEL in its {@link MAKE_KEYWORD}
     * function below.
     */
    bare_label: boolean;
}

/**
 * Holds all PG keywords.
 */
export const PG_KEYWORDS: Catalogue<PG_KEYWORD> = new Catalogue<PG_KEYWORD>();

/**
 * Associates a keyword name with a code and type and defines
 * whether it is a `BARE_LABEL` or a `LABEL`. See {@link BARE_LABEL}
 * and {@link AS_LABEL}.
 * @param id The keyword's reference code
 * @param type The keyword's type
 * @param bare_label
 */
const MAKE_KEYWORD = (id: KEYWORD, type: TYPE, bare_label: boolean) => {
    PG_KEYWORDS.set(KEYWORD[id], {
        id,
        type,
        bare_label
    });
};

MAKE_KEYWORD(KEYWORD.ABORT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ABSENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ABSOLUTE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ACCESS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ACTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ADD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ADMIN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.AFTER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.AGGREGATE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ALL, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ALSO, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ALTER, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ALWAYS, TYPE.UNRESERVED, BARE_LABEL);
/* British spelling */
MAKE_KEYWORD(KEYWORD.ANALYSE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ANALYZE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.AND, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ANY, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ARRAY, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.AS, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.ASC, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ASENSITIVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ASSERTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ASSIGNMENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ASYMMETRIC, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.AT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ATOMIC, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ATTACH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ATTRIBUTE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.AUTHORIZATION, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BACKWARD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BEFORE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BEGIN, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BETWEEN, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BIGINT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BINARY, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BIT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BOOLEAN, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BOTH, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BREADTH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.BY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CACHE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CALL, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CALLED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CASCADE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CASCADED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CASE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CAST, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CATALOG, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CHAIN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CHAR, TYPE.COL_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.CHARACTER, TYPE.COL_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.CHARACTERISTICS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CHECK, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CHECKPOINT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CLASS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CLOSE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CLUSTER, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COALESCE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COLLATE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COLLATION, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COLUMN, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COLUMNS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COMMENT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COMMENTS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COMMIT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COMMITTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COMPRESSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONCURRENTLY, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONDITIONAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONFIGURATION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONFLICT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONNECTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONSTRAINT, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONSTRAINTS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONTENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONTINUE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CONVERSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COPY, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.COST, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CREATE, TYPE.COMMAND, AS_LABEL);
MAKE_KEYWORD(KEYWORD.CROSS, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CSV, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CUBE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_CATALOG, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_DATE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_ROLE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_SCHEMA, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_TIME, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_TIMESTAMP, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURRENT_USER, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CURSOR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.CYCLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DATA, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DATABASE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DAY, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.DEALLOCATE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEC, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DECIMAL, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DECLARE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEFAULT, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEFAULTS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEFERRABLE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEFERRED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEFINER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DELETE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DELIMITER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DELIMITERS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEPENDS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DEPTH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DESC, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DETACH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DICTIONARY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DISABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DISCARD, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DISTINCT, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DO, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DOCUMENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DOMAIN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DOUBLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.DROP, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EACH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ELSE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EMPTY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ENABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ENCODING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ENCRYPTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.END, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ENUM, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ERROR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ESCAPE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EVENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXCEPT, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.EXCLUDE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXCLUDING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXCLUSIVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXECUTE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXISTS, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXPLAIN, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXPRESSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXTENSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXTERNAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.EXTRACT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FALSE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FAMILY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FETCH, TYPE.COMMAND, AS_LABEL);
MAKE_KEYWORD(KEYWORD.FILTER, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.FINALIZE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FIRST, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FLOAT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FOLLOWING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FOR, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.FORCE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FOREIGN, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FORMAT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FORWARD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FREEZE, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FROM, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.FULL, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FUNCTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.FUNCTIONS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GENERATED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GLOBAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GRANT, TYPE.COMMAND, AS_LABEL);
MAKE_KEYWORD(KEYWORD.GRANTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GREATEST, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GROUP, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.GROUPING, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.GROUPS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.HANDLER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.HAVING, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.HEADER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.HOLD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.HOUR, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.IDENTITY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IF, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ILIKE, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IMMEDIATE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IMMUTABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IMPLICIT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IMPORT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IN, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INCLUDE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INCLUDING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INCREMENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INDENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INDEX, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INDEXES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INHERIT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INHERITS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INITIALLY, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INLINE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INNER, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INOUT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INPUT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INSENSITIVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INSERT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INSTEAD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INTEGER, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INTERSECT, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.INTERVAL, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.INTO, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.INVOKER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.IS, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ISNULL, TYPE.TYPE_FUNC_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.ISOLATION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JOIN, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_ARRAY, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_ARRAYAGG, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_EXISTS, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_OBJECT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_OBJECTAGG, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_QUERY, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_SCALAR, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_SERIALIZE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_TABLE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.JSON_VALUE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.KEEP, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.KEY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.KEYS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LABEL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LANGUAGE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LARGE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LAST, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LATERAL, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LEADING, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LEAKPROOF, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LEAST, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LEFT, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LEVEL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LIKE, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LIMIT, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.LISTEN, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOAD, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCALTIME, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCALTIMESTAMP, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCATION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCK, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOCKED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.LOGGED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MAPPING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MATCH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MATCHED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MATERIALIZED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MAXVALUE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MERGE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MERGE_ACTION, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.METHOD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MINUTE, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.MINVALUE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MODE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.MONTH, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.MOVE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NAME, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NAMES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NATIONAL, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NATURAL, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NCHAR, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NESTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NEW, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NEXT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NFC, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NFD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NFKC, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NFKD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NO, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NONE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NORMALIZE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NORMALIZED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NOT, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NOTHING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NOTIFY, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NOTNULL, TYPE.TYPE_FUNC_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.NOWAIT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NULL, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NULLIF, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NULLS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.NUMERIC, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OBJECT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OF, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OFF, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OFFSET, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.OIDS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OLD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OMIT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ON, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.ONLY, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OPERATOR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OPTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OPTIONS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OR, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ORDER, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.ORDINALITY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OTHERS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OUT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OUTER, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OVER, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.OVERLAPS, TYPE.TYPE_FUNC_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.OVERLAY, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OVERRIDING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OWNED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.OWNER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARALLEL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARAMETER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARSER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARTIAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARTITION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PARTITIONS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PASSING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PASSWORD, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PATH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PLACING, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PLAN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PLANS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.POLICY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.POSITION, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRECEDING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRECISION, TYPE.COL_NAME, AS_LABEL);
MAKE_KEYWORD(KEYWORD.PREPARE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PREPARED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRESERVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRIMARY, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRIOR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PRIVILEGES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PROCEDURAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PROCEDURE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PROCEDURES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PROGRAM, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.PUBLICATION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.QUOTE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.QUOTES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RANGE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.READ, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REAL, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REASSIGN, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RECHECK, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RECURSIVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REF, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REFERENCES, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REFERENCING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REFRESH, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REINDEX, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RELATIVE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RELEASE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RENAME, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REPEATABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REPLACE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REPLICA, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RESET, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RESTART, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RESTRICT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RETURN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RETURNING, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.RETURNS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.REVOKE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RIGHT, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROLLBACK, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROLLUP, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROUTINE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROUTINES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROW, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ROWS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.RULE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SAVEPOINT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SCALAR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SCHEMA, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SCHEMAS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SCROLL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SEARCH, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SECOND, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.SECURITY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SELECT, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SEQUENCE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SEQUENCES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SERIALIZABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SERVER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SESSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SESSION_USER, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SET, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SETOF, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SETS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SHARE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SHOW, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SIMILAR, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SIMPLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SKIP, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SMALLINT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SNAPSHOT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SOME, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SOURCE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SPLIT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SQL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STABLE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STANDALONE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.START, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STATEMENT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STATISTICS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STDIN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STDOUT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STORAGE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STORED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STRICT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STRING, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.STRIP, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SUBSCRIPTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SUBSTRING, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SUPPORT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SUM, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SYMMETRIC, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SYSID, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SYSTEM, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.SYSTEM_USER, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TABLE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TABLES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TABLESAMPLE, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TABLESPACE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TARGET, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TEMP, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TEMPLATE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TEMPORARY, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TEXT, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.THEN, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TIES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TIME, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TIMESTAMP, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TO, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.TRAILING, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRANSACTION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRANSFORM, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TREAT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRIGGER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRIM, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRUE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRUNCATE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TRUSTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TYPE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.TYPES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UESCAPE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNBOUNDED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNCOMMITTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNCONDITIONAL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNENCRYPTED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNION, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.UNIQUE, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNKNOWN, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNLISTEN, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNLOGGED, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UNTIL, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.UPDATE, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.USER, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.USING, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VACUUM, TYPE.COMMAND, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VALID, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VALIDATE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VALIDATOR, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VALUE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VALUES, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VARCHAR, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VARIADIC, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VARYING, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.VERBOSE, TYPE.TYPE_FUNC_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VERSION, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VIEW, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VIEWS, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.VOLATILE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.WHEN, TYPE.RESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.WHERE, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.WHITESPACE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.WINDOW, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.WITH, TYPE.RESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.WITHIN, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.WITHOUT, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.WORK, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.WRAPPER, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.WRITE, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XML, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLATTRIBUTES, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLCONCAT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLELEMENT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLEXISTS, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLFOREST, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLNAMESPACES, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLPARSE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLPI, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLROOT, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLSERIALIZE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.XMLTABLE, TYPE.COL_NAME, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.YEAR, TYPE.UNRESERVED, AS_LABEL);
MAKE_KEYWORD(KEYWORD.YES, TYPE.UNRESERVED, BARE_LABEL);
MAKE_KEYWORD(KEYWORD.ZONE, TYPE.UNRESERVED, BARE_LABEL);
